export type PokemonTypeColors = {
  [key: string]: string;
  rock: string,
  ghost: string,
  steel: string,
  water: string,
  grass: string,
  psychic: string,
  ice: string,
  dark: string,
  fairy: string,
  normal: string,
  fighting: string,
  flying: string,
  poison: string,
  ground: string,
  bug: string,
  fire: string,
  electric: string,
  dragon: string,
}

export const PokemonTypeColor: PokemonTypeColors = {
  rock: "#B69E31",
  ghost: "#70559B",
  steel: "#B7B9D0",
  water: "#6493EB",
  grass: "#74CB48",
  psychic: "#FB5584",
  ice: "#9AD6DF",
  dark: "#75574C",
  fairy: "#E69EAC",
  normal: "#AAA67F",
  fighting: "#C12239",
  flying: "#A891EC",
  poison: "#A43E9E",
  ground: "#DEC16B",
  bug: "#A7B723",
  fire: "#F57D31",
  electric: "#F9CF30",
  dragon: "#7037FF",
};
